# Generated by Django 2.1.7 on 2019-02-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pineapple', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='product_name',
        ),
        migrations.DeleteModel(
            name='ProductInstance',
        ),
    ]
